// Drawful-style prompt banks.
//   clean  -> family-friendly, weird & silly
//   adult  -> 18+ party humor: innuendo, dating disasters, drunk shenanigans (drawable, not graphic)
// The host picks which set to use in the lobby (default: adult).

const clean = [
  "A shark riding a skateboard",
  "The world's angriest banana",
  "A robot falling in love with a toaster",
  "A ghost trying to eat soup",
  "Two dinosaurs sharing an umbrella",
  "A cat running a lemonade stand",
  "A wizard stuck in traffic",
  "A snail winning a marathon",
  "An octopus playing all the drums",
  "A vampire at the beach",
  "A grandma breakdancing",
  "A pirate afraid of water",
  "A hamster lifting weights",
  "A cactus giving someone a hug",
  "A penguin on a hot date",
  "A dragon toasting marshmallows",
  "A cloud raining on one small man",
  "A frog wearing a business suit",
  "A giraffe using an ATM",
  "A werewolf getting a haircut",
  "A sloth speed-running a video game",
  "A bee stuck in a bank vault",
  "A mermaid learning to skateboard",
  "A T-rex trying to make its bed",
  "A pigeon delivering the mail",
  "A llama on a rollercoaster",
  "A ninja tripping over a cat",
  "An alien confused by a doorknob",
  "A duck driving a monster truck",
  "A skeleton doing yoga",
  "A whale wearing a tiny hat",
  "A spider knitting a sweater",
  "A moose stuck in a phone booth",
  "A koala judging your life choices",
  "A chicken running for president",
  "A hippo doing ballet",
  "A raccoon robbing a vending machine",
  "A crab playing the violin",
  "A goat texting while walking",
  "A jellyfish going to the gym",
  "A bear ordering a smoothie",
  "A turtle late for work",
  "A flamingo standing on a skateboard",
  "A monkey painting a masterpiece",
  "A walrus at a fancy tea party",
  "An owl pulling an all-nighter",
  "A rhino trying to sneak past a guard",
  "A squirrel hoarding gold coins",
  "A panda eating an entire pizza",
  "A kangaroo boxing a shadow",
  "A lobster sunbathing",
  "A hedgehog rolling down a hill",
  "A parrot leading a book club",
  "A camel selling used cars",
  "A peacock taking a selfie",
  "A haunted vacuum cleaner",
  "A sentient traffic cone",
  "A sandwich that gained consciousness",
  "A very tired mountain",
  "A disco ball at a funeral",
  "A snowman on a tropical vacation",
  "A tornado made entirely of cats",
  "The moon calling in sick",
  "A lighthouse that's scared of the dark",
  "A teapot doing stand-up comedy",
  "A refrigerator running a marathon",
  "A superhero whose power is being average",
  "A detective who is also a baby",
  "A yoga instructor made of spaghetti",
  "A DJ at a library",
  "A very fancy pigeon at the opera",
  "A cowboy riding a giant snail",
  "A mad scientist making pancakes",
  "A clown crying on the subway",
  "A king who lost his crown in the couch",
  "A garden gnome plotting revenge",
  "A microwave that dreams of the ocean",
  "A pumpkin running for mayor",
  "A single sad french fry",
  "A grand piano falling in love",
  "A trampoline for elephants"
];

const adult = [
  "A drunk text you'll regret in the morning",
  "The walk of shame in last night's heels",
  "A one-night stand meeting the parents",
  "Your browser history on a bad night",
  "A Tinder date that goes horribly wrong",
  "Two people making awkward eye contact at a nude beach",
  "Trying to look sexy but pulling a muscle",
  "A stripper who is secretly an accountant",
  "The morning after taco night",
  "A hangover, personified",
  "Sexting the wrong group chat",
  "A midlife-crisis convertible",
  "Getting caught by your roommate",
  "A condom running for public office",
  "The regret after five tequila shots",
  "A booty call at 2am",
  "Dad discovering the internet",
  "A very NSFW Rorschach test",
  "Your ex showing up uninvited",
  "A pole-dancing grandma",
  "Doing your taxes extremely hungover",
  "A romantic dinner that ends in food poisoning",
  "The face you make when the WiFi dies mid-stream",
  "A twerking hippo at last call",
  "Explaining your tattoo to your grandmother",
  "A wine mom on a Tuesday",
  "The group chat after someone got dumped",
  "A dangerously confident bad dancer at the club",
  "Sneaking out after a terrible date",
  "A phone buzzing at the worst possible moment",
  "The gas station bathroom at 3am",
  "A frat house the morning after",
  "Your beer gut on vacation",
  "A questionable decision at the tattoo parlor",
  "The last brain cell at happy hour",
  "A catfish revealing themselves on a blind date",
  "A nudist doing some gardening",
  "A very drunk wedding speech",
  "The office holiday party gone wrong",
  "A hot mess express",
  "A thirst trap gone wrong",
  "Your liver begging for mercy",
  "Two exes matching on a dating app",
  "The 'u up?' text",
  "A dangerously suggestive banana",
  "An awkward third wheel on date night",
  "Getting stuck trying to take off a tight dress",
  "A hangover cure that made everything worse",
  "A drunk person losing a fight with a vending machine",
  "The bathroom line at a nightclub",
  "A questionable Halloween costume",
  "A cougar on the prowl",
  "A DILF at school pickup",
  "Your credit card statement after Vegas",
  "A wine glass the size of a bucket",
  "An intimate moment interrupted by the doorbell",
  "The 'read at 3:47pm' heartbreak",
  "A drunken tattoo of your ex's name",
  "The horror of forgetting you're unmuted on a work call",
  "A very awkward couples massage",
  "Trying to be seductive and knocking over a lamp",
  "A skeleton working the pole",
  "The morning-breath monster",
  "A proud dad bod at the beach",
  "A suspiciously seductive potato",
  "The face of instant regret right after hitting send",
  "Karaoke after way too many shots",
  "A hot tub that's way too crowded",
  "A sugar daddy and his 'business partner'",
  "A love letter written while extremely drunk",
  "Getting friend-zoned in real time",
  "A booze-fueled midnight online shopping spree",
  "Autocorrect turning your text filthy",
  "A striptease that goes very wrong",
  "Explaining a mysterious hickey to your coworkers",
  "The 'delete for everyone' panic",
  "Two hot dogs on a very romantic date",
  "A washed-up rockstar wannabe at 45",
  "A suggestive eggplant",
  "A 4am kebab and deep regret",
  "The drunk uncle at every wedding",
  "Your dating standards after two drinks",
  "A very flirty Grim Reaper",
  "Being left on read, visualized",
  "A spray tan gone horribly orange",
  "A middle finger with a fresh manicure",
  "Trying to sneak a partner past your parents",
  "A very confident nude self-portrait",
  "The '2am, why not' text to your ex",
  "A pole, a spray tan, and bad decisions",
  "Ordering an entire pizza for one at midnight",
  "A drunk bridesmaid",
  "The face when you see the bar tab",
  "A romance novel cover, but make it silly",
  "A raccoon rummaging through your date's trash",
  "Getting matched with your boss on a dating app",
  "A hangover at a kid's birthday party",
  "The morning after a bachelor party",
  "A booty-call ringtone at grandma's house",
  "A cursed unsolicited photo",
  "An awkward boner in a very tight wetsuit",
  "A wine-drunk book club",
  "A very needy ex blowing up your phone",
  "Speed dating disaster",
  "A dad trying to be cool at the club",
  "The 'new phone, who dis?' brush-off",
  "A vodka-fueled 3am cleaning spree",
  "A regrettable group costume",
  "A cat watching you make bad decisions",
  "Trying to twerk and throwing out your back",
  "The face of a bad decision at 1am"
];

module.exports = { clean, adult };
