// Drawful-style prompt bank. Deliberately weird, funny, and drawable.
module.exports = [
  "A shark riding a skateboard",
  "The world's angriest banana",
  "A robot falling in love with a toaster",
  "A ghost trying to eat soup",
  "Two dinosaurs sharing an umbrella",
  "A cat running a lemonade stand",
  "A wizard stuck in traffic",
  "A snail winning a marathon",
  "An octopus playing all the drums",
  "A vampire at the beach",
  "A grandma breakdancing",
  "A pirate afraid of water",
  "A hamster lifting weights",
  "A cactus giving someone a hug",
  "A penguin on a hot date",
  "A dragon toasting marshmallows",
  "A cloud raining on one small man",
  "A frog wearing a business suit",
  "A giraffe using an ATM",
  "A werewolf getting a haircut",
  "A sloth speed-running a video game",
  "A bee stuck in a bank vault",
  "A mermaid learning to skateboard",
  "A T-rex trying to make its bed",
  "A pigeon delivering the mail",
  "A llama on a rollercoaster",
  "A ninja tripping over a cat",
  "An alien confused by a doorknob",
  "A duck driving a monster truck",
  "A skeleton doing yoga",
  "A whale wearing a tiny hat",
  "A spider knitting a sweater",
  "A moose stuck in a phone booth",
  "A koala judging your life choices",
  "A chicken running for president",
  "A hippo doing ballet",
  "A raccoon robbing a vending machine",
  "A crab playing the violin",
  "A goat texting while walking",
  "A jellyfish going to the gym",
  "A bear ordering a smoothie",
  "A turtle late for work",
  "A flamingo standing on a skateboard",
  "A monkey painting a masterpiece",
  "A walrus at a fancy tea party",
  "An owl pulling an all-nighter",
  "A rhino trying to sneak past a guard",
  "A squirrel hoarding gold coins",
  "A panda eating an entire pizza",
  "A kangaroo boxing a shadow",
  "A lobster sunbathing",
  "A hedgehog rolling down a hill",
  "A parrot leading a book club",
  "A camel selling used cars",
  "A beaver building a skyscraper",
  "A peacock taking a selfie",
  "A donkey doing a magic trick",
  "A seal balancing a laptop",
  "An elephant in a tiny car",
  "A fox stealing a pie from a windowsill",
  "A gorilla whispering a secret",
  "A zebra crossing a zebra crossing",
  "A platypus that just saw a ghost",
  "A caterpillar on a treadmill",
  "A swan judging a beauty contest",
  "A bat hanging out at the mall",
  "A porcupine hugging a balloon",
  "A meerkat as a lifeguard",
  "A toad running a food truck",
  "A yak on a first date",
  "An armadillo bowling a strike",
  "A tarantula getting a manicure",
  "A dolphin doing taxes",
  "A badger throwing a tantrum",
  "A lizard sunbathing on a phone",
  "A pufferfish that's very embarrassed",
  "A wombat carrying too many groceries",
  "A chameleon losing at hide and seek",
  "A stork delivering a burrito",
  "A ferret escaping from jail",
  "A haunted vacuum cleaner",
  "A sentient traffic cone",
  "A sandwich that gained consciousness",
  "A very tired mountain",
  "A disco ball at a funeral",
  "A snowman on a tropical vacation",
  "A tornado made entirely of cats",
  "A volcano sneezing",
  "The moon calling in sick",
  "A pair of shoes going on strike",
  "A grumpy rain cloud",
  "A lighthouse that's scared of the dark",
  "A teapot doing stand-up comedy",
  "An escalator to nowhere",
  "A refrigerator running a marathon",
  "A pencil that writes only lies",
  "A balloon afraid of pins",
  "A sock puppet CEO",
  "A haunted bouncy castle",
  "A wizard's very messy kitchen",
  "A knight fighting a mosquito",
  "A superhero whose power is being average",
  "A detective who is also a baby",
  "A yoga instructor made of spaghetti",
  "A DJ at a library",
  "A barber for bald people",
  "A very fancy pigeon at the opera",
  "A traffic jam of unicorns",
  "A cowboy riding a giant snail",
  "A mad scientist making pancakes",
  "A librarian at a rock concert",
  "A clown crying on the subway",
  "A robot learning to dance",
  "A king who lost his crown in the couch",
  "A ballerina hippopotamus at recital",
  "A grumpy toddler ruling a kingdom",
  "A janitor cleaning up after a dragon",
  "A weatherman getting struck by his own forecast",
  "A birthday party for a rock",
  "A garden gnome plotting revenge",
  "A very confused GPS",
  "A haunted photo booth",
  "A microwave that dreams of the ocean",
  "A staircase that leads to another staircase",
  "A snowglobe having a bad day",
  "A pumpkin running for mayor",
  "A candle that's afraid of matches",
  "A mailbox eating the mail",
  "A shopping cart with a mind of its own",
  "A single sad french fry",
  "A cactus on a first date at a balloon store",
  "A ceiling fan that won't stop bragging",
  "A wig blowing away in the wind",
  "A door that only opens for compliments",
  "A pillow fight gone terribly wrong",
  "A bowling ball's graduation day",
  "A grand piano falling in love",
  "A tuba solo that clears the room",
  "A vending machine having a midlife crisis",
  "A snowflake that thinks it's special",
  "A GPS that only speaks in riddles",
  "A trampoline for elephants",
  "A hot air balloon that hates heights"
];
